language: ruby
rvm:
  - 2.7.4
cache:
  bundler: true
services:
    - postgresql
bundler_args: --without development production
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database slam_alphas_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test

env:
  - 'AWS_ACCESS_KEY_ID=ABCDEFGH AWS_SECRET_ACCESS_KEY=ZYWV'
