language: ruby
cache:
  bundler: true
bundler_args: --without development production
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=test
