name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_rails:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ABCDEFGH
      AWS_SECRET_ACCESS_KEY: ZYWV
      RAILS_ENV: test
      SESSION_SECRET: "thisisonlyfortesting"
      DATABASE_TEST_URL: "postgresql://postgres:postgres@localhost:5432/slam_alphas_test?pool=5&timeout=5000"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
    strategy:
      matrix:
        ruby-version: ['2.7.6']
    steps:
      - uses: actions/checkout@v2
      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev
      - name: Install weird things for fog
        run: sudo apt-get -yqq install build-essential libcurl4-openssl-dev && sudo apt-get -yqq install libxml2-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build App
        run: bin/rails db:setup
      - name: Run Tests
        run: bundle exec rspec
